-- Versão reduzida da query em 1602_02.sql
-- Retorna apenas: CODIGO, COR, DESC_COR, CODIGO2_COR, QTDE, DESCRICAO, DT_ENT_ORIG

SELECT
  CO_ITEN.NUMERO,
  CO_ITEN.CODIGO,
  CO_ITEN.COR,
  CADCOR.DESCRICAO AS DESC_COR,
  CADCOR.CODIGO2 AS CODIGO2_COR,
  COALESCE(CO_ITEN.QTDE,0) AS QTDE,
  (CASE WHEN CO_ITEN.TP_ITEM = 'P' THEN PRODUTO.DESCRICAO WHEN CO_ITEN.TP_ITEM = 'M' THEN MATERIAL.DESCRICAO ELSE SERVICO.DESCRICAO END) AS DESCRICAO,
  CO_ITEN.DT_ENT_ORIG
FROM CO_ITEN_001 CO_ITEN
LEFT JOIN CADCOR_001 CADCOR ON (CO_ITEN.COR = CADCOR.COR)
LEFT JOIN MATERIAL_001 MATERIAL ON (MATERIAL.CODIGO = CO_ITEN.CODIGO)
LEFT JOIN PRODUTO_001 PRODUTO ON (PRODUTO.CODIGO = CO_ITEN.CODIGO)
LEFT JOIN SERVICO_001 SERVICO ON (SERVICO.CODIGO = CO_ITEN.CODIGO)
WHERE CO_ITEN.SITUACAO = 'A'
  AND MATERIAL.GRUPO IN ('02')
  AND CO_ITEN.NUMERO IN (:numero)
ORDER BY CO_ITEN.CODIGO;
