-- Versão reduzida da query em 1602_01.sql
-- Retorna apenas: NUMERO, DT_ENTREGA, QTDE_TOTAL, DEPOSITO

SELECT
  COMPRA.NUMERO,
  COMPRA.DT_ENTREGA,
  SUM(COALESCE(CO.QTDE,0)) AS QTDE_TOTAL,
  COMPRA.DEPOSITO
FROM COMPRA_001 COMPRA
LEFT JOIN CO_ITEN_001 CO ON (COMPRA.NUMERO = CO.NUMERO)
LEFT JOIN MATERIAL_001 MATERIAL ON (MATERIAL.CODIGO = CO.CODIGO)
WHERE (COMPRA.TELA <> 'COMOCIMP' OR COMPRA.TELA IS NULL)
  AND CO.SITUACAO = 'A'
  AND MATERIAL.GRUPO IN ('02')
  AND COMPRA.DT_ENTREGA >= current_date
GROUP BY COMPRA.NUMERO, COMPRA.DT_ENTREGA, COMPRA.DEPOSITO
ORDER BY COMPRA.DT_ENTREGA, COMPRA.NUMERO;
