select
	distinct OF1.PEDIDO as PEDIDO
from
	OF1_001 OF1
inner join OF_ITEN_001 OF_ITEN on
	OF_ITEN.NUMERO = OF1.NUMERO
inner join TABPRZ_001 PERIODO on
	PERIODO.PRAZO = OF1.PERIODO
left join PEDIDO_001 PEDIDO on
	PEDIDO.NUMERO = OF1.PEDIDO
left join ENTIDADE_001 CLIENTE on
	CLIENTE.CODCLI = PEDIDO.CODCLI
left join TIPO_001 TIPO on
	TIPO.ID = OF1.ID_TIPO
inner join PRODUTO_001 PRODUTO on
	PRODUTO.CODIGO = OF1.CODIGO
left join ETQ_PROD_001 ETIQUETA on
	ETIQUETA.CODIGO = PRODUTO.ETIQUETA
left join CADCOR_001 COR on
	COR.COR = OF_ITEN.COR
left join PRODCOR PRODCOR on
	PRODCOR.CODIGO = OF1.CODIGO
	and PRODCOR.COR = OF_ITEN.COR
left join MAQUINA_001 MAQUINA on
	MAQUINA.MAQUINA = OF1.MAQUINA
left join MODELO_001 MODELO on
	PRODUTO.MODELO = MODELO.CODIGO
left join EMPRESA EMPRESA on
	OF1.EMP_ID = EMPRESA.ID
left join GRUPO_PA_001 GRUPO_PA on
	PRODUTO.GRUPO = GRUPO_PA.CODIGO
where
	1 = 1
	and OF1.NUMERO >= '000000'
	and OF1.NUMERO <= '999999'
	and OF1.PERIODO >= '0'
	and OF1.PERIODO <= '9999'
	and ((OF1.PEDIDO in (
	select
		NUMERO
	from
		PEDIDO_001
	where
		1 = 1
		and NUMERO in (:sel) ))
		or (exists (
		select
			OF_PED.NUM_OF
		from
			OF_PEDIDO_001 OF_PED
		left join PEDIDO_001 PEDIDO on
			(PEDIDO.NUMERO = OF_PED.PEDIDO)
		where
			OF_PED.NUM_OF = OF1.NUMERO
			and OF_PED.PEDIDO in (:sel) )))
