
--TELA ITEN PEDIDO
-- pesquisa com base no resultado da query p1_1002_acesso.sql colunas = numero 

select

  distinct
  PEDIDO.NUMERO as NUMERO,
  PED_ITEN.CODIGO as CODIGO,
  PED_ITEN.COR as COR,
  CADCOR.DESCRICAO DESCCOR,
  PED_ITEN.TAM as TAM,
  PED_ITEN.QTDE,
  PED_ITEN.QTDE_F QTDE_FAT,
  PED_ITEN.QTDE_ORIG as QTDE_ORIG
from
  PED_ITEN_001 PED_ITEN
inner join PRODUTO_001 PRODUTO on
  (PED_ITEN.CODIGO = PRODUTO.CODIGO)
left join CADCOR_001 CADCOR on
  (PED_ITEN.COR = CADCOR.COR)
left join PEDIDO_001 PEDIDO on
  (PEDIDO.ID = PED_ITEN.ID_PED)
left join REGIAO_001 REG on
  (REG.REGIAO = PEDIDO.TAB_PRE)
left join FAIXA_001 FAIXA on
  (PRODUTO.FAIXA = FAIXA.CODIGO)
left join FAIXA_ITEN_001 FAIXA_ITEN on
  (FAIXA.CODIGO = FAIXA_ITEN.FAIXA
    and FAIXA_ITEN.TAMANHO = PED_ITEN.TAM)
left join TABPRECO_001 TABPRECO on
  (TABPRECO.REGIAO = REG.REGIAO
    and TABPRECO.CODIGO = PED_ITEN.CODIGO
    and TABPRECO.FAIXA_PRECO = FAIXA_ITEN.FAIXA)
left join MARCA_001 MARCA on
  (PRODUTO.MARCA = MARCA.CODIGO)
left join DEPOSITO_001 DEPOSITO on
  (PED_ITEN.DEPOSITO = DEPOSITO.CODIGO)
left join ESPECIE_001 ESPECIE on
  (ESPECIE.CODIGO = PED_ITEN.EMBALAGEM)
left join VALOR_MOEDA_001 VALOR_MOEDA on
  (VALOR_MOEDA.MOEDA = PEDIDO.MOEDA
    and VALOR_MOEDA.DT_COTACAO = PEDIDO.DT_EMISSAO)
left join ETQ_PROD_001 ETQ_PROD on
  (PRODUTO.ETIQUETA = ETQ_PROD.CODIGO)
where
  PED_ITEN.NUMERO in  (:sel)
order by
  PED_ITEN.CODIGO,
  PED_ITEN.COR,
  PED_ITEN.TAM