--ACESSO
select
 PEDIDO.NUMERO as NUMERO
from
 PEDIDO_001 PEDIDO
inner join ENTIDADE_001 CLIENTE on
 (PEDIDO.CODCLI = CLIENTE.CODCLI)
inner join PED_ITEN_001 PED_ITEN on
 (PEDIDO.NUMERO = PED_ITEN.NUMERO)
inner join PRODUTO_001 PRODUTO on
 (PRODUTO.CODIGO = PED_ITEN.CODIGO)
left join CADCEP_001 CADCEP on
 (CLIENTE.CEP = CADCEP.CEP)
left join CIDADE CIDADE on
 (CIDADE.CODIGO = CADCEP.CODMUN)
left join GRUPO_CLI_001 GRUPO_CLI on
 (CLIENTE.GRUPO = GRUPO_CLI.CODIGO)
left join REPRESEN_001 REPRESEN on
 (PEDIDO.CODREP = REPRESEN.CODREP)
left join SITPROD_001 SITPROD on
 (PEDIDO.STATUS = SITPROD.CODIGO)
left join TABPRZ_001 TABPRZ on
 (TABPRZ.PRAZO = PEDIDO.PERIODO)
left join TABPRZ_001 TABPRZ_PD on
 (TABPRZ_PD.PRAZO = PEDIDO.PERIODOPROD)
left join REGIAO_001 REG on
 (REG.REGIAO = PEDIDO.TAB_PRE)
left join GRUPO_PED_001 GRUPO_PED on
 (PEDIDO.GRUPO = GRUPO_PED.CODIGO)
left join COLECAO_001 COLECAO on
 (COLECAO.CODIGO = PEDIDO.COLECAO)
left join HISTCP_001 HISTORICO on
 (HISTORICO.HISTORICO = PEDIDO.HISTORICO)
left join PERFIL_001 PERFIL on
 (PERFIL.CODIGO = CLIENTE.PERFIL)
left join MOEDA_001 MOEDA on
 (PEDIDO.MOEDA = MOEDA.CODMOE )
left join TIPO_001 TIPO on
 (TIPO.ID = PEDIDO.ID_TIPO)
left join MENSAGEM_001 MOTIVO on
 (MOTIVO.CODMEN = PEDIDO.MOTIVO)
left join CLASSE_GER_001 CLASSE on
 (CLASSE.CODIGO = PEDIDO.CLASSE_GER)
left join TABTRAN_001 TABTRAN on
 (TABTRAN.CODIGO = PEDIDO.TAB_TRANS)
left join CAD_COND_PAGTO_001 COND_PAGTO on
 (COND_PAGTO.CODIGO = PEDIDO.COND_PAGTO)
left join OBRA_001 OBRA on
 (OBRA.CODIGO = PEDIDO.OBRA)
left join ENTIDADE_001 RESPONSAVEL on
 (PEDIDO.RESPONSAVEL = RESPONSAVEL.CODCLI)
left join VALOR_MOEDA_001 VALOR_MOEDA on
 (PEDIDO.MOEDA = VALOR_MOEDA.MOEDA
  and PEDIDO.DT_EMISSAO = VALOR_MOEDA.DT_COTACAO)
left join PROD_ECOM_COR_001 PROD_ECOM_COR on
 (PROD_ECOM_COR.CODIGO = PED_ITEN.CODIGO
  and PROD_ECOM_COR.COR = PED_ITEN.COR)
where
 1 = 1
 and PEDIDO.PERIODO >= '0'
 and PEDIDO.PERIODO <= '9999'
 -- Grupo '004' refere-se a pedidos comerciais de meias
 and PRODUTO.GRUPO in ('022', '016')
 and (PEDIDO.TELA = 'VenPedidoGrade'
  or PEDIDO.TELA = 'PEDIDO_SISPLANWEB')
group by
 PEDIDO.NUMERO
having
 SUM(PED_ITEN.QTDE) > 0
 and (SUM(coalesce(PED_ITEN.PRECO, 0) * (coalesce(PED_ITEN.QTDE, 0) + coalesce(PED_ITEN.QTDE_F, 0)))
      - (SUM(coalesce(PED_ITEN.PRECO, 0) * (coalesce(PED_ITEN.QTDE, 0) + coalesce(PED_ITEN.QTDE_F, 0)))
         * ((coalesce(MAX(PEDIDO.PER_DESC), 0) + coalesce(MAX(PEDIDO.PERC_DESC_EMPENHO), 0)) / 100))) >= 0
 and (SUM(coalesce(PED_ITEN.PRECO, 0) * (coalesce(PED_ITEN.QTDE, 0) + coalesce(PED_ITEN.QTDE_F, 0)))
      - (SUM(coalesce(PED_ITEN.PRECO, 0) * (coalesce(PED_ITEN.QTDE, 0) + coalesce(PED_ITEN.QTDE_F, 0)))
         * ((coalesce(MAX(PEDIDO.PER_DESC), 0) + coalesce(MAX(PEDIDO.PERC_DESC_EMPENHO), 0)) / 100))) <= 99999999.99
 